Repository Planner24/24planner.zip, pull requests merged in 2025-03, with the labels that each got.

#1 [P24-1] chore: Husky & GitHub 설정
  .github/pull_request_template.md
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  package-lock.json
  package.json
Labels: chore

#2 [P24-3] fix: Husky 오류 해결
  .gitmessage
  .husky/commit-msg
Labels: fix

#3 [P24-5] chore: [BE] 프로젝트 환경 세팅
  BE/.env.example
  BE/.gitattributes
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/example/p24zip/P24zipApplication.java
  BE/src/main/java/com/example/p24zip/domain/user/controller/AuthController.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/request/RequestDto.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/response/ResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/user/entity/Role.java
  BE/src/main/java/com/example/p24zip/domain/user/entity/User.java
  BE/src/main/java/com/example/p24zip/domain/user/repository/UserRepository.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
  BE/src/main/java/com/example/p24zip/global/config/SecurityConfig.java
  BE/src/main/java/com/example/p24zip/global/entity/BaseTimeEntity.java
  BE/src/main/java/com/example/p24zip/global/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/example/p24zip/global/exception/ResourceNotFoundException.java
  BE/src/main/java/com/example/p24zip/global/response/ApiResponse.java
  BE/src/main/java/com/example/p24zip/global/security/a.txt
  BE/src/main/resources/application.properties
  BE/src/test/java/com/example/p24zip/P24zipApplicationTests.java
Labels: chore

#4 [P24-4] chore: [FE] 프로젝트 환경 세팅
  FE/.gitignore
  FE/README.md
  FE/eslint.config.js
  FE/index.html
  FE/package-lock.json
  FE/package.json
  FE/src/App.css
  FE/src/App.jsx
  FE/src/api/axios.js
  FE/src/component/Footer.jsx
  FE/src/component/Header.jsx
  FE/src/index.css
  FE/src/layout/RootLayout.jsx
  FE/src/main.jsx
  FE/src/pages/Calendar.jsx
  FE/src/pages/Home.jsx
  FE/src/pages/Houses.jsx
  FE/src/pages/Login.jsx
  FE/src/pages/NotFound.jsx
  FE/src/pages/PlanList.jsx
  FE/src/pages/Signup.jsx
  FE/src/pages/TaskGroups.jsx
  FE/src/pages/TaskList.jsx
  FE/src/router/index.jsx
  FE/src/store/slices/authSlice.js
  FE/src/store/store.js
  FE/vite.config.js
  package-lock.json
Labels: chore

#5 [P24-11] chore: DB 도커 세팅 및 prettier 설정
  BE/build.gradle
  BE/compose.yaml
  BE/src/main/java/com/example/p24zip/P24zipApplication.java
  BE/src/main/resources/application.properties
  FE/.prettierrc
  FE/package-lock.json
  FE/package.json
Labels: chore

#6 [P24-12] feat: [BE] 회원가입 기능 완성
  BE/.env.example
  BE/src/main/java/com/example/p24zip/domain/user/controller/UserController.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/request/SignupRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/user/entity/User.java
  BE/src/main/java/com/example/p24zip/domain/user/repository/UserRepository.java
  BE/src/main/java/com/example/p24zip/domain/user/service/UserService.java
  BE/src/main/java/com/example/p24zip/global/exception/CustomException.java
  BE/src/main/java/com/example/p24zip/global/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/example/p24zip/global/response/ApiResponse.java
  BE/src/main/java/com/example/p24zip/global/security/SecurityConfig.java
  BE/src/main/resources/application.properties
Labels: feat

#8 [P24-17] feat: [BE] 사용자 관련 Controller, Service 클래스명 변경
  BE/src/main/java/com/example/p24zip/domain/user/controller/AuthController.java
  BE/src/main/java/com/example/p24zip/domain/user/controller/UserController.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
  BE/src/main/java/com/example/p24zip/domain/user/service/UserService.java
Labels: feat

#10 [P24-19] feat: [BE] 빈값 예외수정 및 SecurityConfig 파일위치 이동
  BE/src/main/java/com/example/p24zip/domain/user/dto/request/SignupRequestDto.java
  BE/src/main/java/com/example/p24zip/global/config/SecurityConfig.java
  BE/src/main/java/com/example/p24zip/global/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/example/p24zip/global/security/SecurityConfig.java
Labels: feat

#9 [P24-18] chore: [FE] 전체적인 레이아웃과 기본 페이지 생성
  FE/public/logo.png
  FE/src/component/Footer.jsx
  FE/src/component/Header.jsx
  FE/src/index.css
  FE/src/layout/RootLayout.jsx
  FE/src/pages/Home.jsx
Labels: chore

#11 [P24-20] feat: [BE] 회원가입 입력 값 예외 처리
  BE/src/main/java/com/example/p24zip/domain/user/dto/request/SignupRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
  BE/src/main/java/com/example/p24zip/global/exception/GlobalExceptionHandler.java
Labels: feat

#13 [p24-16] feat: [BE] 로그인 구현
  .gitignore
  BE/.env.example
  BE/src/main/java/com/example/p24zip/domain/user/controller/AuthController.java
  BE/src/main/java/com/example/p24zip/domain/user/controller/Test.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/request/LoginRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/request/RequestDto.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/response/AccessTokenResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/response/LoginResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/user/entity/User.java
  BE/src/main/java/com/example/p24zip/domain/user/repository/UserRepository.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
  BE/src/main/java/com/example/p24zip/global/config/SecurityConfig.java
  BE/src/main/java/com/example/p24zip/global/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/example/p24zip/global/exception/ResourceNotFoundException.java
  BE/src/main/java/com/example/p24zip/global/exception/TokenException.java
  BE/src/main/java/com/example/p24zip/global/security/CustomUserDetailsService.java
  BE/src/main/java/com/example/p24zip/global/security/a.txt
  BE/src/main/java/com/example/p24zip/global/security/handler/CustomAccessDeniedHandler.java
  BE/src/main/java/com/example/p24zip/global/security/handler/JwtAuthenticationEntryPoint.java
  BE/src/main/java/com/example/p24zip/global/security/jwt/JwtAuthenticationFilter.java
  BE/src/main/java/com/example/p24zip/global/security/jwt/JwtTokenProvider.java
  BE/src/main/resources/application.properties
Labels: fix, feat

#12 [P24-21] feat: [BE] 닉네임 중복 확인 구현 완료
  BE/src/main/java/com/example/p24zip/domain/user/controller/AuthController.java
  BE/src/main/java/com/example/p24zip/domain/user/repository/UserRepository.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
Labels: feat

#14 [P24-22] feat: SMTP 및 Redis 활용한 이메일 인증 구현
  BE/.env.example
  BE/application.yml
  BE/build.gradle
  BE/src/main/java/com/example/p24zip/domain/user/controller/AuthController.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/request/VerifyEmailRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/response/VerifyEmailDataResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
Labels: feat

#17 [P24-25] fix: [BE] redis key 수정
  BE/src/main/java/com/example/p24zip/domain/user/controller/AuthController.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
Labels: fix

#15 [P24-23] feat: [FE] 메인 페이지 디자인 수정 및 에러 페이지 구현
  FE/src/component/Footer.jsx
  FE/src/component/Header.jsx
  FE/src/component/header/HeaderLeft.jsx
  FE/src/component/header/HeaderRight.jsx
  FE/src/component/home/HomeWithAnimation.jsx
  FE/src/component/home/HomeWithoutAnimation.jsx
  FE/src/index.css
  FE/src/layout/RootLayout.jsx
  FE/src/pages/Home.jsx
  FE/src/pages/NotFound.jsx
  FE/src/router/index.jsx
Labels: feat, style, refactor

#18 [P24-26] feat: [BE] 이메일 인증 확인 구현 완료
  BE/src/main/java/com/example/p24zip/domain/user/controller/AuthController.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/request/VerifyEmailRequestCodeDto.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/response/AccessTokenResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/response/LoginResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
  BE/src/main/java/com/example/p24zip/global/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/example/p24zip/global/security/handler/JwtAuthenticationEntryPoint.java
Labels: fix, feat

#19 [P24-14] feat: [FE] 회원가입
  FE/src/api/authApi.js
  FE/src/index.css
  FE/src/pages/Signup.jsx
Labels: fix, feat

#20 [P24-15] feat: [FE] 로그인
  FE/src/api/authApi.js
  FE/src/api/axios.js
  FE/src/pages/Login.jsx
  FE/src/pages/PlanList.jsx
  FE/src/store/slices/authSlice.js
Labels: fix, feat, refactor

#21 [P24-27] fix: [BE] logout exception 수정
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
Labels: fix

#22 [P24-37] refactor: [FE] 메인 페이지, 헤더에 대한 코드 스타일 통일화, 로고 이미지 버그 수정
  FE/src/component/Header.jsx
  FE/src/component/header/HeaderLeft.jsx
  FE/src/component/header/HeaderRight.jsx
  FE/src/component/home/HomeWithAnimation.jsx
  FE/src/component/home/HomeWithoutAnimation.jsx
  FE/src/logo.png
  FE/src/pages/Home.jsx
  FE/src/pages/Login.jsx
  FE/src/pages/NotFound.jsx
  FE/src/pages/Signup.jsx
Labels: fix, refactor

#24 [P24-36] fix: [FE] 로그인 보완
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
  BE/src/main/java/com/example/p24zip/global/security/jwt/JwtTokenProvider.java
  FE/src/api/axios.js
  FE/src/layout/ProtectedLayout.jsx
  FE/src/pages/Login.jsx
  FE/src/router/index.jsx
Labels: fix, feat, refactor

#25 [p24-39] chore: [DP] 1차 자동화 배포
  BE/compose.yaml
  FE/Dockerfile
  FE/nginx.conf
  FE/package-lock.json
  FE/package.json
  FE/vite.config.js
Labels: chore

#27 [P24-41] fix: [DP] deploy.yml 수정
  .github/workflows/deploy.yml
Labels: fix

#28 [P24-41] [DP] deploy.yml 수정
  .github/workflows/deploy.yml
Labels: fix

#30 [P24-38] style: 로그인 CSS 수정
  FE/src/pages/Login.jsx
Labels: style

#31 [P24-42] feat: [FE] 헤더에 URL에 따른 변화와 로그아웃 기능 적용
  FE/src/component/header/HeaderLeft.jsx
  FE/src/component/header/HeaderRight.jsx
Labels: feat

#32 [P24-35] feat: [BE] 이메일 인증 요청 추가 예외 처리
  BE/src/main/java/com/example/p24zip/domain/user/controller/AuthController.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
Labels: feat

#33 [P24-47] fix: [DP] 배포 수정
  BE/src/main/java/com/example/p24zip/global/config/SecurityConfig.java
  BE/src/main/resources/application.properties
Labels: fix

#34 [P24-46] feat: [BE] 이사 플랜 Entity 생성
  BE/src/main/java/com/example/p24zip/domain/movingPlan/entity/MovingPlan.java
Labels: feat

#35 [P24-44] fix: [FE] 회원가입 이메일 인증 남은 시간 오류 해결
  BE/src/main/java/com/example/p24zip/domain/user/dto/response/VerifyEmailDataResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
  BE/src/main/resources/application.properties
  FE/src/pages/Signup.jsx
Labels: fix

#37 [P24-49] feat: [BE] 이사 플랜 Repository 생성
  BE/src/main/java/com/example/p24zip/domain/movingPlan/repository/MovingPlanRepository.java
Labels: feat

#39 [P24-43] feat: [BE] 할 일 api 구현
  BE/src/main/java/com/example/p24zip/domain/schedule/controller/ScheduleController.java
  BE/src/main/java/com/example/p24zip/domain/schedule/dto/request/ScheduleRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/schedule/dto/response/DayScheduleListResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/schedule/dto/response/DayScheduleResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/schedule/dto/response/MonthScheduleListResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/schedule/dto/response/ScheduleResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/schedule/entity/Schedule.java
  BE/src/main/java/com/example/p24zip/domain/schedule/repository/ScheduleRepository.java
  BE/src/main/java/com/example/p24zip/domain/schedule/service/ScheduleService.java
Labels: fix, feat, refactor

#40 [P24-53] feat: [BE] 체크그룹, 체크포인트 Entity 및 Repository 생성
  BE/src/main/java/com/example/p24zip/domain/task/entity/Task.java
  BE/src/main/java/com/example/p24zip/domain/task/repository/TaskRepository.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/entity/TaskGroup.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/repository/TaskGroupRepository.java
Labels: feat

#41 [P24-55] feat: [BE] 공통 예외 처리 추가
  BE/src/main/java/com/example/p24zip/global/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/example/p24zip/global/security/jwt/JwtTokenProvider.java
Labels: feat

#43 [P24-48] feat: [BE] 집 생성 및 집 리스트 조회 구현 완료
  BE/build.gradle
  BE/src/main/java/com/example/p24zip/domain/house/controller/HouseController.java
  BE/src/main/java/com/example/p24zip/domain/house/dto/request/AddHouseRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/house/dto/response/AddHouseResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/house/dto/response/HouseListResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/house/dto/response/KaKaoGeocodeResponse.java
  BE/src/main/java/com/example/p24zip/domain/house/entity/House.java
  BE/src/main/java/com/example/p24zip/domain/house/repository/HouseRepository.java
  BE/src/main/java/com/example/p24zip/domain/house/service/HouseService.java
  BE/src/main/java/com/example/p24zip/global/exception/GeocoderExceptionHandler.java
  BE/src/main/java/com/example/p24zip/global/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/example/p24zip/global/security/jwt/JwtTokenProvider.java
Labels: feat

#45 [P24-58] fix: [DP] 지도 배포 문제 해결
  .env.example
  .github/workflows/deploy.yml
  FE/Dockerfile
  FE/src/component/map/MapSidebar.jsx
  docker-compose.yml
Labels: feat

#47 [P24-56] feat: [BE] 체크포인트 API 구현
  BE/src/main/java/com/example/p24zip/domain/movingPlan/controller/MovingPlanController.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/dto/response/MovingPlanResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/entity/MovingPlan.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/service/MovingPlanService.java
  BE/src/main/java/com/example/p24zip/domain/task/controller/TaskController.java
  BE/src/main/java/com/example/p24zip/domain/task/dto/request/TaskCompleteRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/task/dto/request/TaskRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/task/dto/response/TaskListResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/task/dto/response/TaskResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/task/entity/Task.java
  BE/src/main/java/com/example/p24zip/domain/task/repository/TaskRepository.java
  BE/src/main/java/com/example/p24zip/domain/task/service/TaskService.java
  BE/src/main/java/com/example/p24zip/global/security/jwt/JwtTokenProvider.java
Labels: feat, refactor

#48 [P24-57] feat: [BE] 체크그룹 API 구현
  BE/src/main/java/com/example/p24zip/domain/task/repository/TaskRepository.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/controller/TaskGroupController.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/dto/request/TaskGroupMemoUpdateRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/dto/request/TaskGroupRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/dto/response/TaskGroupDetailResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/dto/response/TaskGroupListResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/dto/response/TaskGroupMemoUpdateResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/dto/response/TaskGroupResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/entity/TaskGroup.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/repository/TaskGroupRepository.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/service/TaskGroupService.java
Labels: feat, refactor

#49 [P24-61] feat: [FE] 지도 페이지 완성
  FE/src/api/mapApi.js
  FE/src/component/map/Map.jsx
  FE/src/component/map/MapModal.jsx
Labels: feat

#50 [P24-65] fix: [FE] 지도 페이지 버튼 클릭 수정
  FE/src/component/map/Map.jsx
  FE/src/component/map/MapModal.jsx
Labels: fix

#51 [P24-62] feat: [BE] 집 관련 READ, PATCH, DELETE 구현 완료
  .env.example
  BE/src/main/java/com/example/p24zip/domain/house/controller/HouseController.java
  BE/src/main/java/com/example/p24zip/domain/house/dto/request/ChangeHouseContentRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/house/dto/request/ChangeHouseNicknameRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/house/dto/response/ChangeHouseContentResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/house/dto/response/ChangeHouseNicknameResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/house/dto/response/GetHouseDetailsResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/house/entity/House.java
  BE/src/main/java/com/example/p24zip/domain/house/service/HouseService.java
  BE/src/main/java/com/example/p24zip/global/exception/GlobalExceptionHandler.java
Labels: feat

#52 [P24-64] refactor: [BE] 할 일 api 보완
  BE/src/main/java/com/example/p24zip/domain/schedule/controller/ScheduleController.java
  BE/src/main/java/com/example/p24zip/domain/schedule/repository/ScheduleRepository.java
  BE/src/main/java/com/example/p24zip/domain/schedule/service/ScheduleService.java
Labels: refactor

#53 [P24-67] feat: [BE] 집 관련 예외처리 추가
  BE/src/main/java/com/example/p24zip/domain/house/controller/HouseController.java
  BE/src/main/java/com/example/p24zip/domain/house/service/HouseService.java
Labels: feat

#54 [P24-63] feat: [BE] movingPlanId 검증을 위한 validator 구현 및 적용
  BE/src/main/java/com/example/p24zip/domain/house/controller/HouseController.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/controller/MovingPlanController.java
  BE/src/main/java/com/example/p24zip/domain/schedule/controller/ScheduleController.java
  BE/src/main/java/com/example/p24zip/domain/task/controller/TaskController.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/controller/TaskGroupController.java
  BE/src/main/java/com/example/p24zip/global/validator/MovingPlanValidator.java
Labels: feat

#55 [P24-71] feat: [BE] 집 상세주소 수정 구현 완료
  BE/src/main/java/com/example/p24zip/domain/house/controller/HouseController.java
  BE/src/main/java/com/example/p24zip/domain/house/dto/request/AddHouseRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/house/dto/request/ChangeHouseDetailAddressRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/house/dto/response/ChangeHouseDetailAddressResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/house/entity/House.java
  BE/src/main/java/com/example/p24zip/domain/house/service/HouseService.java
Labels: feat

#56 [P24-72] fix: 예외 처리 메서드 로직 수정
  BE/src/main/java/com/example/p24zip/domain/house/service/HouseService.java
Labels: fix

#57 [P24-66] feat: [FE] 지도 페이지 보완 및 지도 세부 페이지 완성
  FE/src/api/mapApi.js
  FE/src/component/map/Map.jsx
  FE/src/component/map/MapModal.jsx
  FE/src/component/map/MapSidebar.jsx
  FE/src/pages/Houses.jsx
Labels: fix, feat

#59 [P24-74] fix: [FE] 레이아웃 전역 수정
  FE/src/layout/RootLayout.jsx
Labels: fix

#60 [P24-75] fix: [FE] 집 삭제 및 수정 재구성
  FE/src/component/map/MapModal.jsx
  FE/src/component/map/MapSidebar.jsx
  FE/src/layout/RootLayout.jsx
Labels: fix

#61 [P24-76] fix: [FE] 지도 페이지 수정 및 에러 페이지 이동
  FE/src/component/map/Map.jsx
Labels: fix

#62 [P24-70] feat: [FE] 이사 플랜 페이지 구현
  FE/src/api/planApi.js
  FE/src/component/plan/Plan.jsx
  FE/src/component/plan/PlanCreator.jsx
  FE/src/layout/RootLayout.jsx
  FE/src/pages/PlanList.jsx
  FE/src/pages/PlanSetting.jsx
  FE/src/router/index.jsx
Labels: feat

#63 [P24-78] fix: [FE] 지도 중복 생성 에러 수정
  FE/src/component/map/MapModal.jsx
Labels: fix

#68 [P24-80] fix: [FE] 지도 상세페이지 수정 버튼 엔터 수정
  FE/src/component/map/Map.jsx
  FE/src/component/map/MapModal.jsx
  FE/src/component/map/MapSidebar.jsx
Labels: fix

#65 [P24-69] feat: [FE] 체크그룹 생성 및 체크그룹 리스트 조회 하는 페이지 구현 완료
  FE/src/api/taskGroupApi.js
  FE/src/component/TaskGroup/TaskGroupBox.jsx
  FE/src/pages/TaskGroups.jsx
Labels: feat

#67 [P24-77] feat: [FE] 이사 플랜 설정 페이지 구현
  BE/src/main/java/com/example/p24zip/domain/movingPlan/controller/MovingPlanController.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/entity/MovingPlan.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/service/MovingPlanService.java
  FE/src/api/planApi.js
  FE/src/component/plan/Plan.jsx
  FE/src/component/plan/PlanCreator.jsx
  FE/src/pages/PlanList.jsx
  FE/src/pages/PlanSetting.jsx
Labels: feat

#66 [P24-68] feat: [FE] 체크포인트 페이지 구현
  BE/src/main/java/com/example/p24zip/domain/task/dto/response/TaskListResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/task/service/TaskService.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/dto/request/TaskGroupRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/dto/response/TaskGroupMemoUpdateResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/entity/TaskGroup.java
  FE/src/api/taskApi.js
  FE/src/api/taskGroupApi.js
  FE/src/component/taskList/Task.jsx
  FE/src/component/taskList/TaskGroupInfo.jsx
  FE/src/component/taskList/TaskGroupMemo.jsx
  FE/src/component/taskList/TaskListSection.jsx
  FE/src/pages/TaskList.jsx
Labels: fix, feat, refactor

#70 [P24-82] fix: [FE] taskGroupApi 오류 해결 및 체크 그룹 navigate 추가
  FE/src/api/taskGroupApi.js
  FE/src/component/TaskGroup/TaskGroupBox.jsx
Labels: fix

#64 [P24-51] feat: [FE] 달력 페이지 구현
  FE/package-lock.json
  FE/package.json
  FE/src/component/Footer.jsx
  FE/src/component/calendar/CalendarColorModal.jsx
  FE/src/component/calendar/CalendarContent.jsx
  FE/src/component/calendar/CalendarModal.jsx
  FE/src/component/calendar/CalendarModalDatePicker.jsx
  FE/src/component/calendar/CalendarSidebar.jsx
  FE/src/component/calendar/popover/PopoverComponent.jsx
  FE/src/component/calendar/popover/PopoverUtilComponent.jsx
  FE/src/component/calendar/svg/ChevronLeftSvg.jsx
  FE/src/component/calendar/svg/ChevronRightSvg.jsx
  FE/src/index.css
  FE/src/layout/RootLayout.jsx
  FE/src/pages/Calendar.jsx
  FE/src/pages/Home.jsx
  FE/src/store/slices/popoverSlice.js
  FE/src/store/store.js
Labels: feat

#71 [P24-86] fix: [FE] 지도 메인 페이지 및 상세 페이지 보완 및 완성
  FE/src/component/map/Map.jsx
  FE/src/component/map/MapModal.jsx
Labels: fix

#72 [P24-85] fix: [FE] 체크포인트 보완
  BE/src/main/java/com/example/p24zip/domain/schedule/dto/request/ScheduleRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/schedule/entity/Schedule.java
  BE/src/main/java/com/example/p24zip/domain/task/dto/request/TaskRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/task/entity/Task.java
  BE/src/main/java/com/example/p24zip/domain/taskGroup/dto/request/TaskGroupMemoUpdateRequestDto.java
  FE/src/component/taskList/Task.jsx
  FE/src/component/taskList/TaskListSection.jsx
Labels: fix, feat

#73 [P24-83] feat: [FE] API 구현에 따른 메인, 헤더 페이지 대응
  FE/src/component/Footer.jsx
  FE/src/component/Header.jsx
  FE/src/component/header/HeaderLeft.jsx
  FE/src/component/header/HeaderRight.jsx
  FE/src/pages/Home.jsx
  FE/src/store/slices/planForHeaderSlice.js
  FE/src/store/store.js
Labels: fix, feat, refactor

#74 [P24-87] feat: [FE] 로그인 상태로 로그인, 회원가입 페이지 접근 제한
  FE/src/pages/Login.jsx
  FE/src/pages/Signup.jsx
Labels: feat

#75 [P24-88] fix: [FE] 이사 플랜 관련 보완
  BE/src/main/java/com/example/p24zip/domain/movingPlan/dto/request/MovingPlanRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/entity/MovingPlan.java
  FE/src/component/plan/Plan.jsx
  FE/src/component/plan/PlanCreator.jsx
Labels: fix, feat, style

#76 [P24-84] feat: [FE] 체크 그룹 보완 사항
  BE/src/main/java/com/example/p24zip/domain/house/entity/House.java
  FE/src/component/TaskGroup/TaskGroupBox.jsx
  FE/src/pages/TaskGroups.jsx
Labels: feat

#77 [P24-91] fix: [FE] 브라우저 창 닫은 후 액세스 토큰 미삭제 오류 해결
  FE/src/api/axios.js
Labels: fix

#78 [P24-93] feat: [FE] 이사 플랜 관련 추가 보완
  FE/src/component/plan/PlanCreator.jsx
  FE/src/pages/PlanSetting.jsx
Labels: feat, style

#79 [P24-92] style: [FE] 살 곳 정하기 및 체크 그룹 페이지 CSS 변경
  FE/src/component/TaskGroup/TaskGroupBox.jsx
  FE/src/component/map/Map.jsx
  FE/src/pages/TaskGroups.jsx
Labels: feat, style

#81 [P24-79] feat: [FE] 달력 페이지 API 연동
  BE/src/main/java/com/example/p24zip/domain/schedule/dto/response/DayScheduleListResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/schedule/dto/response/DayScheduleResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/schedule/service/ScheduleService.java
  FE/src/api/scheduleApi.js
  FE/src/component/calendar/CalendarColorModal.jsx
  FE/src/component/calendar/CalendarContent.jsx
  FE/src/component/calendar/CalendarModal.jsx
  FE/src/component/calendar/CalendarSidebar.jsx
  FE/src/component/calendar/popover/PopoverComponent.jsx
  FE/src/component/calendar/util/calendarUtil.js
  FE/src/pages/Calendar.jsx
Labels: feat, refactor

#83 [P24-98] feat: [FE] 헤더 페이지 추가 기능 링크
  FE/src/component/header/HeaderLeft.jsx
  FE/src/component/header/HeaderRight.jsx
Labels: feat

#84 P24-89 feat: [BE/FE] 실시간 채팅 구현
  .env.example
  .github/workflows/deploy.yml
  BE/build.gradle
  BE/src/main/java/com/example/p24zip/P24zipApplication.java
  BE/src/main/java/com/example/p24zip/domain/chat/controller/ChatController.java
  BE/src/main/java/com/example/p24zip/domain/chat/dto/request/MessageRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/chat/dto/response/ChatsResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/chat/dto/response/MessageResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/chat/entity/Chat.java
  BE/src/main/java/com/example/p24zip/domain/chat/repository/ChatRepository.java
  BE/src/main/java/com/example/p24zip/domain/chat/service/ChatService.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/response/LoginResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
  BE/src/main/java/com/example/p24zip/global/MyChannelInterceptor.java
  BE/src/main/java/com/example/p24zip/global/config/SecurityConfig.java
  BE/src/main/java/com/example/p24zip/global/config/WebConfig.java
  FE/.env.example
  FE/Dockerfile
  FE/index.html
  FE/package-lock.json
  FE/package.json
  FE/src/api/chatApi.js
  FE/src/index.css
  FE/src/pages/Chat.jsx
  FE/src/pages/Login.jsx
  FE/src/router/index.jsx
  FE/src/store/slices/authSlice.js
  FE/vite.config.js
  docker-compose.yml
Labels: fix, feat

#82 [P24-97] style: [FE] 달력 추가 디자인 적용
  FE/src/component/calendar/CalendarColorModal.jsx
  FE/src/component/calendar/CalendarContent.jsx
  FE/src/component/calendar/CalendarHeader.jsx
  FE/src/component/calendar/CalendarMain.jsx
  FE/src/component/calendar/CalendarModal.jsx
  FE/src/component/calendar/CalendarModalDatePicker.jsx
  FE/src/component/calendar/CalendarSidebar.jsx
  FE/src/component/calendar/popover/PopoverComponent.jsx
  FE/src/component/calendar/popover/PopoverUtilComponent.jsx
  FE/src/component/calendar/style/calendarMain.css
  FE/src/component/calendar/svg/ChevronLeftSvg.jsx
  FE/src/component/calendar/svg/ChevronRightSvg.jsx
  FE/src/component/calendar/svg/LoadingCircle.jsx
  FE/src/component/calendar/util/calendarUtil.js
  FE/src/component/calendar/util/scheduleUtil.js
  FE/src/index.css
  FE/src/pages/Calendar.jsx
Labels: style, refactor
