Repository Planner24/24planner.zip, pull requests merged in 2025-04, with the labels that each got.

#85 [P24-94] feat: [BE/FE] 동거인 기능 구현
  BE/src/main/java/com/example/p24zip/domain/movingPlan/controller/HousemateController.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/controller/InvitationController.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/controller/MovingPlanController.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/dto/request/HousemateInvitationRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/dto/request/MovingPlanRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/dto/response/HousemateInvitationAcceptResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/dto/response/HousemateInvitationResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/dto/response/HousemateInvitationValidateResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/dto/response/HousemateResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/dto/response/MovingPlanHousemateResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/dto/response/MovingPlanOwnerResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/entity/Housemate.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/entity/MovingPlan.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/repository/HousemateRepository.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/repository/MovingPlanRepository.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/service/HousemateService.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/service/InvitationService.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/service/MovingPlanService.java
  BE/src/main/java/com/example/p24zip/global/config/SecurityConfig.java
  BE/src/main/java/com/example/p24zip/global/security/jwt/JwtTokenProvider.java
  BE/src/main/java/com/example/p24zip/global/validator/MovingPlanValidator.java
  FE/src/api/housemateApi.js
  FE/src/api/planApi.js
  FE/src/component/header/HeaderRight.jsx
  FE/src/component/plan/Housemate.jsx
  FE/src/component/plan/HousemateListSection.jsx
  FE/src/pages/Invite.jsx
  FE/src/pages/Login.jsx
  FE/src/pages/PlanList.jsx
  FE/src/pages/PlanSetting.jsx
  FE/src/pages/Signup.jsx
  FE/src/router/index.jsx
Labels: feat, refactor

#86 P24-99 fix: [BE/FE] 실시간 구현 수정
  BE/src/main/java/com/example/p24zip/domain/chat/controller/ChatController.java
  BE/src/main/java/com/example/p24zip/domain/chat/service/ChatService.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
  FE/src/pages/Chat.jsx
Labels: fix

#89 [P24-101] fix: 배포 오류 해결
  FE/src/component/TaskGroup/TaskGroupBox.jsx
  FE/src/pages/TaskGroups.jsx
  FE/src/store/store.js
Labels: feat

#88 [P24-100] refactor: [FE] 메인 페이지, 달력 페이지, CSS 최적화
  FE/src/component/calendar/CalendarMain.jsx
  FE/src/component/calendar/calendarHeader/CalendarHeader.jsx
  FE/src/component/calendar/content/CalendarContent.jsx
  FE/src/component/calendar/modal/CalendarColorModal.jsx
  FE/src/component/calendar/modal/CalendarModal.jsx
  FE/src/component/calendar/modal/CalendarModalDatePicker.jsx
  FE/src/component/calendar/sidebar/CalendarSidebar.jsx
  FE/src/component/calendar/style/calendarContent.css
  FE/src/component/calendar/style/calendarMain.css
  FE/src/component/calendar/style/calendarModalDatePicker.css
  FE/src/component/home/HomeWithAnimation.jsx
  FE/src/component/home/style/homeAnimation.css
  FE/src/index.css
  FE/src/pages/Calendar.jsx
Labels: fix, refactor

#90 [P24-102] fix: 배포 에러 해결2
  FE/src/pages/NewPassword.jsx
  FE/src/router/index.jsx
Labels: fix

#91 [P24-102] fix: [BE] 에러 해결
  BE/src/main/java/com/example/p24zip/domain/user/dto/response/VerifyEmailDataResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
Labels: fix

#93 P24-105 fix: [BE/FE] 실시간 채팅 에러 처리 수정
  BE/src/main/java/com/example/p24zip/domain/chat/controller/ChatController.java
  BE/src/main/java/com/example/p24zip/domain/chat/dto/response/ChatsErrorResponseDto.java
  BE/src/main/java/com/example/p24zip/global/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/example/p24zip/global/exception/StompTokenException.java
  FE/src/component/map/Map.jsx
  FE/src/pages/Chat.jsx
Labels: fix

#92 [P24-106] fix: [FE] 메인, 헤더, 달력, 오류 페이지 개선
  FE/src/component/calendar/content/CalendarContent.jsx
  FE/src/component/calendar/modal/CalendarModal.jsx
  FE/src/component/calendar/sidebar/CalendarSidebar.jsx
  FE/src/component/calendar/style/calendarContent.css
  FE/src/component/header/HeaderLeft.jsx
  FE/src/component/header/HeaderRight.jsx
  FE/src/pages/NotFound.jsx
Labels: fix

#94 [P24-109] fix: [FE/BE] 이사 플랜 보완
  BE/src/main/java/com/example/p24zip/domain/movingPlan/entity/MovingPlan.java
  FE/src/component/plan/Plan.jsx
Labels: fix, feat

#95 [P24-108] fix: [FE] 체크포인트 중복 제출 및 카운팅 오류 해결
  FE/src/component/taskList/Task.jsx
  FE/src/component/taskList/TaskListSection.jsx
Labels: fix

#96 [P24-110] fix: [FE] 지도 현재 위치 수정
  FE/src/component/map/Map.jsx
Labels: fix

#97 [P24-104] feat: [FE] 동거인 초대 링크 공유 카카오톡 미리보기 개선
  BE/src/main/java/com/example/p24zip/domain/movingPlan/controller/InvitationController.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/dto/request/HousemateInvitationRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/service/InvitationService.java
  FE/index.html
  FE/public/logo.png
  FE/src/api/housemateApi.js
  FE/src/component/plan/HousemateListSection.jsx
  FE/src/pages/Invite.jsx
Labels: feat

#98 [P24-96] feat: [BE/FE] 카카오 소셜로그인 구현
  .env.example
  .github/workflows/deploy.yml
  BE/.env.example
  BE/build.gradle
  BE/src/main/java/com/example/p24zip/domain/user/controller/AuthController.java
  BE/src/main/java/com/example/p24zip/domain/user/controller/Test.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/request/OAuthSignupRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/user/dto/response/OAuthSignupResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/user/entity/User.java
  BE/src/main/java/com/example/p24zip/domain/user/handler/CustomOAuthLoginFailureHandler.java
  BE/src/main/java/com/example/p24zip/domain/user/handler/CustomOAuthLoginSuccessHandler.java
  BE/src/main/java/com/example/p24zip/domain/user/provider/CustomOAuth2User.java
  BE/src/main/java/com/example/p24zip/domain/user/provider/KakaoOAuthUserInfo.java
  BE/src/main/java/com/example/p24zip/domain/user/provider/OAuthUserInfo.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
  BE/src/main/java/com/example/p24zip/domain/user/service/CustomOAuth2UserService.java
  BE/src/main/java/com/example/p24zip/domain/user/service/TempUserService.java
  BE/src/main/java/com/example/p24zip/global/config/SecurityConfig.java
  BE/src/main/java/com/example/p24zip/global/exception/AdditionalInfoRequiredException.java
  BE/src/main/java/com/example/p24zip/global/security/jwt/JwtTokenProvider.java
  BE/src/main/resources/application.properties
  FE/src/api/authApi.js
  FE/src/assets/kakaoLogin.png
  FE/src/component/login/KakaoLogin.jsx
  FE/src/pages/Login.jsx
  FE/src/pages/LoginRedirect.jsx
  FE/src/pages/SignupAdditionalInfo.jsx
  FE/src/router/index.jsx
Labels: fix, feat, refactor

#99 [P24-111] feat: [BE/FE] 실시간 채팅 날짜 추가
  BE/src/main/java/com/example/p24zip/domain/chat/dto/response/MessageResponseDto.java
  BE/src/main/java/com/example/p24zip/domain/chat/service/ChatService.java
  FE/src/pages/Chat.jsx
Labels: feat

#100 [P24-112] fix: [FE] 헤더 로고 링크 추가
  FE/src/component/header/HeaderLeft.jsx
  FE/src/component/header/HeaderRight.jsx
Labels: fix

#101 [P24-115] fix: [FE] 달력 버그 수정
  FE/src/component/calendar/CalendarMain.jsx
  FE/src/component/calendar/calendarHeader/CalendarHeader.jsx
Labels: fix

#104 [P24-117] feat: [FE] 로그인 페이지 비밀번호 찾기 버튼 추가
  FE/src/pages/Login.jsx
Labels: feat

#106 [P24-107] feat: [BE/FE] 회원 탈퇴
  BE/src/main/java/com/example/p24zip/domain/chat/repository/ChatRepository.java
  BE/src/main/java/com/example/p24zip/domain/movingPlan/repository/HousemateRepository.java
  BE/src/main/java/com/example/p24zip/domain/user/controller/UserController.java
  BE/src/main/java/com/example/p24zip/domain/user/entity/User.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
  FE/src/api/userApi.js
  FE/src/pages/Mypage.jsx
Labels: feat

#107 [P24-113] feat: [FE] TanStack Query를 통한 일정 비동기 처리 캐시
  FE/package-lock.json
  FE/package.json
  FE/src/App.jsx
  FE/src/component/calendar/CalendarMain.jsx
  FE/src/component/calendar/content/CalendarContent.jsx
  FE/src/component/calendar/modal/CalendarModal.jsx
  FE/src/component/calendar/sidebar/CalendarSidebar.jsx
  FE/src/pages/Calendar.jsx
Labels: feat

#109 Update README.md
  README.md
Labels: docs

#108 [P24-121] fix: [FE] 달력 버그 수정
  FE/src/component/calendar/CalendarMain.jsx
Labels: fix

#111 [P24-122] fix: [FE] 달력 버그 수정
  FE/src/component/calendar/content/CalendarContent.jsx
Labels: fix

#113 [P24-123] style: [FE] 파비콘 추가
  FE/index.html
  FE/public/zip_logo.png
Labels: style

#114 [P24-119] fix: [BE/FE] 비밀번호 찾기(이메일 인증) 에러 처리
  BE/src/main/java/com/example/p24zip/domain/user/dto/request/ChangePasswordRequestDto.java
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
  BE/src/main/java/com/example/p24zip/global/config/SecurityConfig.java
  BE/src/main/java/com/example/p24zip/global/security/jwt/JwtTokenProvider.java
  FE/src/api/userApi.js
  FE/src/component/user/Password.jsx
  FE/src/kakao_favicon.ico
  FE/src/pages/FindPassword.jsx
  FE/src/pages/Mypage.jsx
  FE/src/pages/NewPassword.jsx
Labels: fix

#115 [P24-124] style: [FE] 마이페이지 스타일 및 errorElement 처리
  FE/src/pages/Mypage.jsx
  FE/src/router/index.jsx
Labels: style

#116 Update README.md
  README.md
Labels: docs

#118 [P24-125] fix: [BE] 실시간 채팅 변수명 수정
  BE/src/main/java/com/example/p24zip/domain/chat/controller/ChatController.java
  BE/src/main/java/com/example/p24zip/domain/chat/dto/response/ChatsResponseDto.java
Labels: fix

#119 [P24-116] fix: [FE] 일부 수정 사항 적용
  BE/src/main/java/com/example/p24zip/domain/user/service/AuthService.java
  FE/src/component/calendar/modal/CalendarModal.jsx
  FE/src/component/calendar/sidebar/CalendarSidebar.jsx
  FE/src/pages/Login.jsx
  FE/src/pages/Mypage.jsx
Labels: fix
